### ISSUE TITLE
What does the AUTH_SECRET refer to? 

### ISSUE THREAD

**Issue by Sylvie-J** [Davronov-Alimardon/canva-clone#1]
Hi! 

I'm playing around with this project and I'm trying to setup the environment variables. 
I'm struggling to see what the AUTH_SECRET variable refers to and was hoping you could point me in the right direction? 

This is a really good codebase btw :) 

J

**Comment by Davronov-Alimardon** [comment]
Hi!

The only environment variable that is mandatory is the AUTH_SECRET. This is a random value used by the library to encrypt tokens and email verification hashes. This is important for encryption, I recommend exploring the Auth.js library for details:

Link: https://authjs.dev/getting-started/installation?framework=next.js#setup-environment
