### ISSUE TITLE
add the new feature

### ISSUE THREAD

**Issue by cuongngm** [Davronov-Alimardon/canva-clone#2]
thank you for this interesting project. i think it would be great if there was a feature to suggest alignment according to available blocks when users move new blocks on the editor screen (suggestion to align 2 blocks together, suggestion to align 1 block according to an available block, etc...) like on canva. i wonder if you plan to develop this feature?

**Comment by Davronov-Alimardon** [comment]
Thank you for your interest in the project and for your suggestion. At the moment, I am occupied with other tasks and do not have the capacity to implement new features. However, I welcome contributions from the community. If you have ideas and would like to implement this feature, please feel free to submit a pull request. Your contributions are greatly appreciated!
